#PBS -N bcl2fastq
#PBS -l walltime=48:00:00,nodes=1:ppn=20
#PBS -e logs
#PBS -o logs

if [ "x$PBS_O_WORKDIR" != "x" ]; then
	cd $PBS_O_WORKDIR
fi
export PATH=$PATH:/usr/local/bin

if [ ! -d logs ]; then mkdir logs; fi

cmd="bcl2fastq \
--sample-sheet ${ss} \
--use-bases-mask Y151,I12,Y151 \
--minimum-trimmed-read-length 1 \
--mask-short-adapter-reads 1 \
-o ${o} \
--loading-threads 8 \
--processing-threads 8 \
--writing-threads 4"

date >& 2
echo "Executing: $cmd" >& 2
eval $cmd
date >& 2
