#!/usr/bin/env python
import sys
from sequence_processing_pipeline.main import main as spp_main
import logging


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)

    spp_main('a', 'b', 'c', 'd', 'e', 'f', sys.argv[1])
